language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp
- composer self-update
- composer install
- nvm install 9
- npm install --global grunt-cli
- npm install

script:
- grunt

after_success:
- grunt deploy

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182