language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp
- composer self-update
- composer install

before_script:
- mkdir build

script:
- cp vendor/redaxscript/redaxscript-service/images build/images --recursive
- cp vendor/redaxscript/redaxscript-service/news build/news --recursive
- cp vendor/redaxscript/redaxscript-service/version build/version --recursive
- cp vendor/redaxscript/redaxscript-service/xml build/xml --recursive

after_success:
- lftp $FTP_URL -e "glob -d mirror build . --reverse --delete-first --parallel=10 && exit"

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182