language: php

php: 7.2

addons:
 apt:
  packages:
  - lftp

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 12
- npm install --global grunt-cli
- npm install

script:
- grunt

after_success:
- grunt deploy

notifications:
 email:
 - team@redaxscript.com
